import 'globals.dart';

String signInString = lang=='en'?'SIGN IN':'ĐĂNG NHẬP';
String signUPString = lang=='en'?'SIGN UP':'ĐĂNG KÝ';
String emailString = 'E-Mail';
String passWordString = lang=='en'?'Password':"Mật khẩu";
String forgotPassString = lang=='en'?"Forgot Password ?" : "Quên mật khẩu ?";
String connectWithString = lang=='en'?"Or connect with":"Hoặc đăng nhập qua";
String doNotHaveAccountString = lang=='en'?"Don't have an account? ":"Chưa có tài khoản?";
String signUpString = lang=='en'?'Sign up': 'Đăng ký';
String nameString = lang=='en'?'Name':'Tên';
String haveAccountString = lang=='en'?"Have an account? ":"Đã có tài khoản?";
String signINString = lang=='en'?'Sign in': 'Đăng nhập';
String passDescription = lang=='en'?'If you need help resetting your password, we can help by sending you a link to reset it.':
'Nếu bạn muốn đặt lại mật khẩu, chúng tôi có thể gửi link đặt lại mật khẩu cho bạn.';
String sentString = lang=='en'?'SENT':'GỬI';
String enterPhoneNumberString = lang=='en'?'To continue enter your phone number':'Để tiếp tục hãy nhập số điện thoại';
String phoneString = lang=='en'?'Phone':'SĐT';
String continueString = lang=='en'?'CONTINUE':'TIẾP TỤC';
String verifyNumberString = lang=='en'?'Verify phone number':'Xác nhận số điện thoại';
String resentCodeString = lang=='en'?'Resent Code':'Gửi lại mã';
String verifyDoneString = lang=='en'?'Verify Done!':'Xác nhận hoàn tất!';
String haveGoodExperienceString = lang=='en'?'Have a good experrience with our app!':'Chúc bạn có những trải nghiệm tốt với ứng dụng của chúng tôi';
String doneString = lang=='en'?'Done':'Hoàn tất';
String homeString = lang=='en'?'Home':'Trang chủ';
String exploreString = lang=='en'?'Explore':'Khám phá';
String radioString = "Radio";
String accountString = lang=='en'?'Account':'Tài khoản';
String newAlbumString = lang=='en'?'New Albums':'Album mới';
String viewAllString = lang=='en'?'View all':'Xem tất cả';
String recentMusicString = lang=='en'?'Recently Music':'Gần đây';
String chartString = lang=='en'?'Chart':'Bảng xếp hạng';
String topicString = lang=='en'?'Topic':'Chủ đề';
String searchString = lang=='en'?'Search':'Tìm kiếm';
String cancelString = lang=='en'?'Cancel':'Huỷ bỏ';
String historyString = lang=='en'?'History':'Lịch sử';
String topSearchString = lang=='en'?'Top Searching':'Tìm kiếm nhiều nhất';
String allString = lang=='en'?'All':'Tất cả';
String songString = lang=='en'?'Song':'Bài hát';
String artistString = lang=='en'?'Artist':'Nghệ sĩ';
String albumString = 'Album';
String showMoreString = lang == 'en' ? "Show more" : "Xem thêm";
String suggestionsString = lang == 'en' ? "Suggestions" : "Gợi ý";
String lyricString = lang == 'en' ? "Lyrics" : "Lời";
String playlistString = "Playlist";
String followString = lang == 'en' ? "Follow" : "Theo dõi";
String followerString = lang == 'en' ? "Follower" : "Người theo dõi";
String followingString = lang == 'en' ? "Following" : "Đang theo dõi";
String libraryString = lang== 'en' ? 'Library' : 'Thư viện';
String myPlaylistString = lang == 'en' ? "My playlist" : "Playlist của tôi";
String downloadString = lang == 'en' ? "Download" : "Tải về";
String recentActivityString = lang == 'en' ? 'Recent Activity' : 'Hoạt động gần đây';
String settingString = lang == 'en' ? 'Setting' : 'Cài đặt';
String notificationString = lang == 'en' ? 'Notification' : 'Thông báo';
String displayLanguageString = lang == 'en' ? 'Display Language' : 'Ngôn ngữ';
String versionString = lang == 'en' ? 'Version' : 'Phiên bản';
String signOutString = lang == 'en' ? 'SIGN OUT' : 'ĐĂNG XUẤT';
String editString = lang == 'en' ? 'Edit' : 'Chỉnh sửa';
String userNameString = lang == 'en' ? 'Username' : 'Tên';
String genderString = lang == 'en' ? 'Gender' : 'Giới tính';
String dateBirthString = lang == 'en' ? 'Date of birth' : 'Ngày sinh';
String changePasswordString = lang == 'en' ? 'Change Password' : 'Đổi mật khẩu';
String downloadToString = lang == 'en' ? 'DOWNLOAD TO' : "TẢI VỀ";
String freeString = lang == 'en' ? 'Free' : "Miễn phí";
String throughoutString1 = "128 Kbps";
String throughoutString2 = "320 Kbps";
String losslessString = "Lossless";
String vipString = "VIP";
String vipAccountString = lang == 'en' ? 'VIP account' : 'Tài khoản VIP';
String shareToString = lang == 'en' ? 'SHARE TO' : "CHIA SẺ";
String facebookString = "FaceBook";
String googleString = "Google +";
String twitterString = "Twitter";
String copyLinkString = lang == 'en' ? "Copy Link" : "Sao chép đường dẫn";
String addNewPlaylistString = lang == 'en' ? "Add New Playlist" : "Thêm Playlist mới";
String createPlaylistString = lang == 'en' ? "CREATE PLAYLIST" : "TẠO PLAYLIST";
String hintPlaylistTextField = lang == 'en' ? "Enter your playlist name" : "Nhập tên playlist";
String okString = "OK";
String somethingWrong = "Something went wrong";
String unfollowingString = lang == 'en' ? "Unfollow" : "Huỷ theo dõi";
String errorString1 = lang == 'en' ? 'Error' : 'Lỗi';
String errorDetail1 = lang == 'en' ? "Something went wrong" : "Có gì đó sai sót";
String errorString2 = lang == 'en' ? 'No internet' : 'Không có Internet';
String errorDetail2 = lang == 'en' ? 'Please check your internet connection' : 'Hãy kiểm tra kết nối Internet của bạn';

String emptyStringError = lang == 'en' ? "Given input is empty" : 'Đầu vào không hợp lệ';
String badFormatError = lang == 'en' ? 'The email address is badly formatted.' : 'Email sai định dạng';
String notRegisteredError = lang == 'en' ? "Email is not registered" : 'Email chưa được đăng ký';
String incorrectPasswordError = lang == 'en' ? 'Incorrect password' : 'Mật khẩu không chính xác';
String defaultError = lang == 'en' ? 'Error' : 'Lỗi';
